"""empty message

Revision ID: 2ed12c545ef6
Revises: d14334360c7f
Create Date: 2024-06-05 09:45:20.897848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed12c545ef6'
down_revision = 'd14334360c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('release', sa.Date(), nullable=False),
    sa.Column('director', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters_films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters_films')
    op.drop_table('films')
    # ### end Alembic commands ###
