"""empty message

Revision ID: e493a87e242a
Revises: 2ed12c545ef6
Create Date: 2024-06-05 10:24:54.850011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e493a87e242a'
down_revision = '2ed12c545ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('body')
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
