"""empty message

Revision ID: ed09fdef8855
Revises: c007042891cd
Create Date: 2024-05-31 16:59:25.215838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed09fdef8855'
down_revision = 'c007042891cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('diemeter', sa.Float(), nullable=False))
        batch_op.drop_constraint('posts_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('posts_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('diemeter')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
